import Head from 'next/head'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
import '../styles/globals.css'
import { RecoilRoot } from 'recoil';
import { useEffect, useState } from 'react';
import { NavermapsProvider } from 'react-naver-maps';

function MyApp({ Component, pageProps }) {
    const [loaded, setLoaded] = useState(false);
    useEffect(() => setLoaded(true), []);

    return (
        <>
            <RecoilRoot>
                <NavermapsProvider
                    ncpClientId='an7y5ntcz5'
                >
                    <Head>
                        <title>Map Utils</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                        
                    </Head>
                    
                    <Header />
                    {
                        loaded ? <Component {...pageProps} />
                        : <>loading</> 
                    }
                    <Footer />
                </NavermapsProvider>
            </RecoilRoot>
        </>
    )
}

export default MyApp
