import Head from 'next/head'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
import '../styles/globals.css'
import { RecoilRoot } from 'recoil';

function MyApp({ Component, pageProps }) {
return (
    <>
        <RecoilRoot>
            <Head>
                <title>Map Utils</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Header />
            <Component {...pageProps} /> 
            <Footer />
        </RecoilRoot>
    </>

)}

export default MyApp
