import Head from 'next/head'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
import '../styles/globals.css'
import { RecoilRoot } from 'recoil';
import { useEffect, useState } from 'react';

function MyApp({ Component, pageProps }) {
    const [loaded, setLoaded] = useState(false);
    useEffect(() => setLoaded(true), []);

    return (
        <>
            <RecoilRoot>
                <Head>
                    <script
                        type="text/javascript"
                        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=86679c06b544978b5a247df1e7091067&autload=false"
                    ></script>

                    <title>Map Utils</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                
                <Header />
                {
                    loaded ? <Component {...pageProps} />
                    : <>loading</> 
                }
                <Footer />
            </RecoilRoot>
        </>
    )
}

export default MyApp
